### ISSUE TITLE
FR/Suggestion: images in AWS Public ECR

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#104]
Hello Conduktor team.

Currently the docker images are on dockerhub, which makes totally sense for users given that's the default registry used by `docker`.
However, for AWS users, in order to work around potential rate limiting in both deployment or CI steps, due to Dockerhub changes, having these images in public ECR would remove that rate limit all together.
It's also very cheap to host these (relatively I suppose), and when the source of the pull is on AWS' network, it's free.

It **should** be as easy as adding a couple commands to your current build process

```shell
# Log into AWS Public ECR
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${PUBLIC_REGISTRY}

# Add a tag to the newly built image(s)
docker tag <built image> public.ecr.aws/conduktor/conduktor-platform:${tag}
docker push public.ecr.aws/conduktor/conduktor-platform:${tag}
# Publish the images manifest list.
docker manifest create public.ecr.aws/conduktor/conduktor-platform:${tag} [...] # that's to publish the image list
docker manifest push public.ecr.aws/conduktor/conduktor-platform:${tag}
```

**Comment by qboileau** [comment]
Hi @JohnPreston, 

thank you for your suggestion, we are actually working on having our own public repository that should not have rate-limits to host Conduktor-Platform along with other images/tools. 

We will still publish on DockerHub too.
