### ISSUE TITLE
FR: set timezone and date format

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#114]
Hi Conduktor team,

Currently the timezone used seems to inherit the timezone of the underlying instance.
It'd be useful to be able to be able to change that.

Also in the topics timeline, the time is using AM/PM markers (either that or I have an exact 12h of time difference ..) which is very annoying (to me that is) and so I'd rather be able to change to using a 24h format just like it is in the timestamps.

Thank you,

**Comment by twobeeb** [comment]
Hi @JohnPreston,
Thanks for your feedback, we have planned the following:
1. Sort term: Fix the timeline to be consistent with the rest of the platform (h24 instead of AM/PM)
2. Later: user preference to pick select the timezone
