### ISSUE TITLE
FR: Add little `?` next to settings for topic creation

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#115]
Hi Conduktor team,

We noticed that, for example, when creating a new topic, the `cleanup.policy` values in the UI are `Retention` & `Compaction`.
Some users reported that this differs from the "real values" which are `delete` and `compact`.
So generally when trying to make things user-friendly, either use the correct semantic words or add a little `?` that people can hover onto and show the real semantic names, along with a link to the Kafka documentation explaining the impact of the property.

Thank you :)

**Comment by qboileau** [comment]
cc @twobeeb and @guizmaii

**Comment by JamesW1** [comment]
Note the semantics (delete) and (compact) have now been post-fixed to these labels. Thanks!
