### ISSUE TITLE
Following projects did not launch correctly: authenticator

### ISSUE THREAD

**Issue by deepakn27** [conduktor/conduktor-platform#118]
I am using free mode of conduktor-platform. 

When I run ./run-local.sh. I get below error on UI.

Oops, something went wrong...
Following projects did not launch correctly: authenticator

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/65304516/204853674-da7c8738-5adb-4563-85ff-abe51fcef2f1.png">

**Comment by mitchell-h** [comment]
Hi @deepakn27,
Would it be possible to give us the out put of `docker-compose logs`?  You can send them to support @ conduktor dot io and please reference this issue.

The web UI does not give enough information to accurately debug this issue.

**Comment by deepakn27** [comment]
Sure, @mitchell-h , I have sent logs to mailto support@conduktor.io
