### ISSUE TITLE
FR: UI still shows disabled features & shouldn't

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#120]
Hi Conduktor team,

Issue: After disabling some Conduktor features (i.e disabling testing on a production instance), the modules are still visible in the UI. From a UI point of view, that's not a big problem, but from a UX point of view, it's misleading. Clicking on these takes you back to the home page and makes users feel like it's a bug, where it's a feature.
If possible the UI should at least gray out they feature, or hide them.

Thank you,

**Comment by rokh-conduktor** [comment]
Hi Johon, 

Thanks for your feedback !

we have in mind to provide a proper module disabling feature for an upcoming version of conduktor with slick routing and so on.
For now, disabling modules is not a feature of the product yet but a technical workaround for resource management.

I Will keep you in the loop when we will release the final module disabling feature :+1: .
Best,
