### ISSUE TITLE
Permission denied on startup.

### ISSUE THREAD

**Issue by waqar-ahmed** [conduktor/conduktor-platform#137]
Hi,

I am getting the following exception whenever I run conductor-platform docker:

**thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:365:13**

Also, attached is the image from the logs:
![image](https://user-images.githubusercontent.com/16003307/221439818-0b53005e-74b1-4b46-be5d-d4190922180b.png)

 I tried running it separately as a docker as well but same error. But if I run docker as privilieged, it works:
 
`docker run --rm -p 8097:8080 --privileged --security-opt="seccomp=unconfined" conduktor/conduktor-platform:latest`

  It would be great if anyone can guide me how to fix it.

Versions:

- docker-compose: version 1.28.5, build c4eb3a1f
- Docker version: 20.10.5, build 55c4c88
- OS: Ubuntu 20.04.2 LTS

Thank you.

**Comment by qboileau** [comment]
Hi, 
thanks for the report, we are aware of this issue on some setups. 
Have you try to update your docker engine and compose ? 
This might resolve the issue without `--privileged --security-opt="seccomp=unconfined"` flags.
