### ISSUE TITLE
Conduktor is not working properly with Kraft

### ISSUE THREAD

**Issue by CN-0** [conduktor/conduktor-platform#139]
Conduktor Version: 1.12.1
Kafka Version: 3.3.2
When using conduktor with kafka in kraft mode we are facing the following issues:

1. In Monitoring Section Overview Tab Active Controller Count Keeps on Changing and giving alert  Active Controller Count != 1. this should be case when using with zookeeper but in kraft mode Active Controller Count can be more than 1 and also Active Controller Count keeps on changing i think it is an issue in Conduktor
2. In Console Section Brokers Tab the Leader Broker Keeps on changing, but it is not the case in cluster the Leader is constant i think this is an issue in Conduktor due to kraft mode

Please fix these issues as kraft mode is made production ready

**Comment by JamesW1** [comment]
Hi @CN-0 - thanks for this feedback, it has been logged with our Product team for review. In the future, please raise issues through our official support channel:
https://support.conduktor.io/
