### ISSUE TITLE
Question | Schema registry - reference

### ISSUE THREAD

**Issue by GoncaloPT** [conduktor/conduktor-platform#164]
Hi, I've been trying out conduktor and I've bumped into a a problem: I cannot create, using the UI, schemas when they reference another one. I always get "Attention: Invalid schema: Undefined name: XXXX" even though the schema exists in the same namespace. I've already tried variations, with or without the namespace with the same result.

Following some confluent documentation, i've also tried to use a schema definition that includes both "schema" and "references" 
both the UI rejects that format. The format is:
```json
{
"schema":{
...
},
"references:"[
{
...
}
]

}
```
Is this something you don't want to support? 
Thanks.

Articles/posts:
https://forum.confluent.io/t/schema-registry-is-not-accepting-a-type-by-reference/1526/3
https://akhq.io/docs/configuration/schema-registry/schema-references.html
https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/#avro-unions-with-schema-references

**Comment by twobeeb** [comment]
Hello @GoncaloPT, thanks for your message. 

While this is something we have on our radar, we are not currently supporting Schema References. 

There's a good chance we will implement this at some point in the near future, but our roadmap is packed full of other shiny things that we must address first: https://product.conduktor.help/tabs/1-in-development

Feedback like yours helps us a lot in our prioritization process.

Thanks
