### ISSUE TITLE
JMX-Exporter configuration from Aiven Service

### ISSUE THREAD

**Issue by remynollet** [conduktor/conduktor-platform#20]
Please, how can we setup the configuration of the jmx-exporter in the platform-config.yaml

**Comment by mbaechler** [comment]
Hi Remy,
For now there's no way to configure the port for jmx_exporter and as far as I understand, Aiven does not use port 9001 for that.
Moreover, we didn't test if metrics provided by Aiven are the same we expect so it's likely to break anyway.
We'll support Aiven at some point and let you know then.

**Comment by remynollet** [comment]
https://help.aiven.io/en/articles/2684968-accessing-jmx-metrics-via-jolokia

**Comment by mbaechler** [comment]
The best resource I found is actually this one: https://docs.aiven.io/docs/platform/howto/integrations/prometheus-metrics.html

**Comment by rokh-conduktor** [comment]
you can use `jmxScrapePort` from  see : https://github.com/conduktor/conduktor-platform/blob/b774b51825c6b800938ccc7e7df8851c481897e5/doc/Configuration.md#cluster-configuration-properties
