### ISSUE TITLE
Docker image 1.0.2 cannot start correctly

### ISSUE THREAD

**Issue by andres-JT** [conduktor/conduktor-platform#41]
Hi there! We are trying to test your docker image in Ubuntu and we have this error. Also, is there any env var to disable monitoring and avoid starting prometheus exporters, alertmanager and all this stuff??

ERROR c.l.k.ConsumerGroupCollector$ akka://kafka-lag-exporter/user/consumer-group-collector-local - Supervisor RestartSupervisor saw failure [96]: Failed to create new KafkaAdminClient org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
conduktor                                          | 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:479)
conduktor                                          | 	at org.apache.kafka.clients.admin.Admin.create(Admin.java:61)
conduktor                                          | 	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
conduktor                                          | 	at com.lightbend.kafkalagexporter.KafkaClient$.createAdminClient(KafkaClient.scala:120)
conduktor                                          | 	at com.lightbend.kafkalagexporter.KafkaClient$.apply(KafkaClient.scala:55)
conduktor                                          | 	at com.lightbend.kafkalagexporter.MainApp$.$anonfun$start$1(MainApp.scala:37)
conduktor                                          | 	at com.lightbend.kafkalagexporter.ConsumerGroupCollector$.$anonfun$init$1(ConsumerGroupCollector.scala:149)
conduktor                                          | 	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
conduktor                                          | 	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
conduktor                                          | 	at akka.actor.typed.internal.RestartSupervisor.restartCompleted(Supervision.scala:383)
conduktor                                          | 	at akka.actor.typed.internal.RestartSupervisor.aroundReceive(Supervision.scala:243)
conduktor                                          | 	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
conduktor                                          | 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
conduktor                                          | 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
conduktor                                          | 	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
conduktor                                          | 	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)

**Comment by hvgirish** [comment]
the error seems to be this 
```
Caused by: org.apache.kafka.common.config.ConfigException: The specified value of default.api.timeout.ms must be no smaller than the value of request.timeout.ms.
	at org.apache.kafka.clients.admin.KafkaAdminClient.configureDefaultApiTimeoutMs(KafkaAdminClient.java:547)
	at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:516)
```

because the AdminClient properties are wrong
```
	client.dns.lookup = default
	client.id = conduktor
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 5000 <-- This is smaller than 
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 10000 <-- this
	retries = 0
	retry.backoff.ms = 1000
```

I tried looking to customise this but didn't find a way to pass properties that would be set on the AdminClient 🤷

**Comment by framiere** [comment]
@twobeeb

**Comment by trobert** [comment]
As a workaround, you should not set `default.api.timeout.ms` in `default-platform-config.yaml` to a lower value than 10000.
(Currently `request.timeout.ms=10000` is enforced by https://github.com/seglo/kafka-lag-exporter)
