### ISSUE TITLE
FR: document how to init/use external psql database

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#43]
Hello Conduktor team,

Going through the logs, I can see that upon starting the application, it performs a lot of PSQL init, etc.

For production deployments, as a user, I might want to use an externally managed PSQL database for HA and performance.
Is this something undocumented or not yet available for configuration ?

Thank you!

**Comment by mbaechler** [comment]
Hi John,
It's something we are working on.
We will document that once ready.

**Comment by JohnPreston** [comment]
I can see that on startup it generates a few files for PSQL localhost config etc, i.e. in the admin.yml file.
So my updated assumption is that the CDK_IN_FILE does not yet have a section to influence that. My guess is that's because there is a different config for different functionalities of the application? (`auditlog`, `permission` etc,)

**Comment by JohnPreston** [comment]
@qboileau @mbaechler @sderosiaux 
Okay, tested it with Aurora PSQL 14.4 and it worked **on the first try** so very great job to all :rocket: 
Thank you very much :pray:
