### ISSUE TITLE
FR: implement / document a healthcheck

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#50]
Hello

As best practice, setting a health check for applications allows to actively check that the core functions are working properly (i.e. if depends on a DB, that it can connect to it).
Most web applications implement such endpoint in order to probe the availability of it.

Currently had to set the endpoint for health check on`/home/login`, given that `/` returns a redirect.

Setting it in docker-compose with the `healtcheck` service configuration would tell everyone that's in place and how it works.

Please do tell if more context is needed.

**Comment by framiere** [comment]
@rokh-conduktor

**Comment by qboileau** [comment]
Hi @JohnPreston,

actually, conduktor-platform already have some health check endpoints, but they are not documented yet (will fix that asap).

On a running platform you have : 
- `/platform/api/modules/health/live` as a liveness endpoint
- `/platform/api/modules/health/ready` as a startup probe

**Comment by framiere** [comment]
Hi @qboileau, can we add them directly in the `docker-compose.yml` file too ?
