### ISSUE TITLE
FR: consumer groups offset reset

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#56]
Hello

I could find the following:https://docs.conduktor.io/features/topics-management/how-to#how-to-reset-the-offsets-of-a-topic 
However, in the platform, I could not find any such option to reset the offsets of a consumer group.

It'd be great to be able to reset the offset for a consumer group for a given topic via Conduktor: either reset offsets for all partitions or, reset for individual partitions.

Thanks!

**Comment by guizmaii** [comment]
Hey @JohnPreston,

In version `1.1.2` of Console, we provide a minimal "Reset Offsets" feature
For now, you can only reset the offsets of all topics and only to the earliest or latest offsets

We'll deliver the full "Reset Offsets" feature set in the next release
You will be able to choose which topics and which partitions you want to reset and the selection of the offset to reset to will be more fine-grained thanks to more possibilities


Cheers,
Jules

**Comment by JohnPreston** [comment]
Hey @guizmaii 
QQ: is the `latest` image pointing to the latest semantically versioned image? Just to be sure!
Thank you!

**Comment by guizmaii** [comment]
Hey :)

> QQ: is the latest image pointing to the latest semantically versioned image? 

Yes, it must. Don't forget to force the pull if you're running it with Docker: `docker run --pull=always`. Sometimes, Docker seems to be lazy and doesn't pull the latest version tagged as the `latest`

**Comment by JohnPreston** [comment]
@mitchell-h that does help with finer grain.
One feature we have/had in AKHQ is to filter by datetime which makes the filtering even easier. So I'd add that to the "feature list" but the shift by is already very helpful, thanks,

**Comment by mitchell-h** [comment]
Good idea.  I'll add it to the feature list.

**Comment by twobeeb** [comment]
Closing ticket as we released 4 reset strategies for now:
- Earliest
- Latest
- Shift By
- To Datetime
