### ISSUE TITLE
FR: Console view of ACLs

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#57]
Hello,

Currently, if we select a given topic, we can see the ACLs set for a given Kafka user.
It'd be very helpful for troubleshooting purposes to have another "tab" added to the topics/consumer groups/connect list, that would allow viewing all ACLs sets for all users.

Thank you!

**Comment by JohnPreston** [comment]
@twobeeb Am I good to close this? That seems to be there in 1.6.0 :)

**Comment by JamesW1** [comment]
Closing this now as the use case is satisfied. Thanks @JohnPreston
