### ISSUE TITLE
UI FR: better topic names display

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#59]
Hello,

Yet another bit of UX feedback related to the UI.

Currently one cannot resize the tab for the topic names. Then once in the topic menu, the name is truncated as well.
It'd be nice to be able to resize the column in the topics list view, and maybe if keeping the names truncated, have a nice `copy-paste` button to put the full name in the clipboard.

Thank you!

**Comment by rokh-conduktor** [comment]
Hello @JohnPreston, it's now in our roadmap thanks for the feedback!
