### ISSUE TITLE
FR: Audit Logs coverage

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#89]
Hello team.

As an administrator, I'd want the following things to be logged

* Connection (Log In)
* Changes to clusters
  * Create / modify cluster configuration
* Changes to RBAC
  * Create/Delete group
  * Add/Remove users to group
  * Add/Remove policies / permissions to group
  * Change of user role (i.e. user A changes user B from Member to Admin)
* Changes to topics
  * Create/Delete Topic
  * Published messages
  * Deleted messages
* Updates to consumer groups
  * Offset reset on topic/partitions
* Schemas
  * Create schema
  * Delete schema
  * Change compatibility
* Connect
  * Connectors operations (create/pause/restart) & CRUD operations
* Testing
  * Workspace creation
  * Tests updates
  * Tests executions
  * Creation of new cluster - when not using an org level defined one.

And generally, all resources created in the platform should be considered an auditable resource.
If there is a way to have an "access log" similar to web server logs, where we'd get time - user - resource - action that'd be acceptable.

It'd be useful to have audit logs streamed to a "secretly defined" kafka topic.

Thanks a lot for your consideration,

**Comment by twobeeb** [comment]
Hey @JohnPreston,
everything you suggest here is very logical and it's actually already planned, we got you covered.

Our first iteration (weeks) will store AuditLogs events in an internal table. 
After that (months), we are thinking "external integrations": Kafka topic being one of them.

Stay tuned,
Julien

**Comment by JohnPreston** [comment]
Looking forward to it @twobeeb . @mitchell-h would have reported the regression I uncovered yesterday. I just thought that'd be the good time to add these things in.

As for streaming / export to external places (S3 for example), that's not urgent, if it's in the DB, we have daily backups to ensure we wouldn't lose too much.

**Comment by JohnPreston** [comment]
So very near all there in 1.10, great work :rocket:

**Comment by JamesW1** [comment]
See the full list of existing audit log events here:
https://docs.conduktor.io/platform/admin/audit-log/

While most are now covered, there are still some gaps. This has been logged with the product team.

Closing as we want to funnel all feedback/support through specific channels.
